### ISSUE TITLE
Create Document for Troubleshooting Pending Submissions

### ISSUE THREAD

**Issue by hh** [kubernetes-sigs/verify-conformance#148]
Having some issues with verify-conformance check stuck in pending event though "All requirements (15) have passed":

From https://github.com/cncf/k8s-conformance/pull/3125#issuecomment-2095182064

![image](https://github.com/cncf-infra/verify-conformance/assets/31331/97a82bb4-8dd7-48fe-aa1f-8fc6ecc5e3ca)

Would be good to document the process for troubleshooting when the pipeline gets stuck.

**Comment by BobyMCbobs** [comment]
The issue was that the submissions such as [cncf/k8s-conformance#3125](https://github.com/cncf/k8s-conformance/pull/3125) have failed 1000 times and had been stuck on pending.
Seeing errors like this
```
time="2024-05-12T08:19:43Z" level=info msg="CreateStatus(cncf, k8s-conformance, 7b3957bfab9778c1797cc88039da72bb91b72a74, {success  All checks are passing verify-conf
ormance})" client=github
time="2024-05-12T08:20:03Z" level=info msg="error running checks on PR: status code 422 not one of [201], body: {\"message\":\"Validation Failed\",\"errors\":[{\"resource\":\"Status\",\"code\":\"custom\",\"message\":\"This SHA and context has reached the maximum number of statuses.\"}],\"documentation_url\":\"https://docs.github.com/rest/commits/statuses#create-a-commit-status\"}" plugin=verify-conformance-release
```
Now that the submission is successful and reached the quota, it can’t be set as successful.
I’ve added a gate to try to prevent this in the future.
Given the GitHub commit status cannot be removed, the path forward is for the submissions to be recreated or merged anyways (given labels and comments).

Since the bot still passes the submissions and this is a partially-GitHub based fault, I would consider the submissions to be mergeable.
